main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
main.o: main.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/init.h \
  /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/MOD5441X/include/pitr_sem.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h stepper.h
stepper.o: stepper.cpp /Users/dciliske/nndk/include/predef.h \
  /Users/dciliske/nndk/include/constants.h \
  /Users/dciliske/nndk/include/ucos.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/include/system.h \
  /Users/dciliske/nndk/include/pins.h \
  /Users/dciliske/nndk/MOD5441X/include/pinconstant.h \
  /Users/dciliske/nndk/include/utils.h \
  /Users/dciliske/nndk/include/nettypes.h \
  /Users/dciliske/nndk/include/basictypes.h \
  /Users/dciliske/nndk/MOD5441X/include/sim.h \
  /Users/dciliske/nndk/MOD5441X/include/sim5441x.h \
  /Users/dciliske/nndk/include/cfinter.h \
  /Users/dciliske/nndk/MOD5441X/include/intcdefs.h stepper.h
